title: The Ruby Museum
email: dfmoreto@gmail.com
url: "https://therubymuseum.com"
author: itsmeaga1n
twitter:
  username: itsmeaga1n
  card: summary
plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
# Exclude these files from production site

collections:
  museum:
    output: true

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - node_modules
